FROM ubuntu:14.04

# Setup repos
RUN apt-get update && apt-get install -y apt-transport-https \
	&& echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list \
	&& apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 \
	&& apt-get update

# Install packages
RUN apt-get -y install openjdk-7-jdk sbt git

# Setup user
RUN adduser --gecos FALSE --disabled-password build
USER build
WORKDIR /home/build
